### PR TITLE
Add 30 seconds of code

### PR DESCRIPTION
**Pull request by Chalarangelo**
[30 seconds of code](https://www.30secondsofcode.org/) is a collection of short code snippets and blogs, focused mainly on web development and especially JavaScript. We recently added an RSS feed to our website and I think this would fit right into this list.

### CODE REVIEW

**Comment by impressivewebs** [comment]
> [30 seconds of code](https://www.30secondsofcode.org/) is a collection of short code snippets and blogs, focused mainly on web development and especially JavaScript. We recently added an RSS feed to our website and I think this would fit right into this list.

Hi @Chalarangelo, thanks for the suggestion. I will review it and let you know. Just an FYI - while trying to load the page in Brave browser, I only got a blank page. I had to disable Brave's built in ad blocker to see the page. Seems to work ok in Chrome though.

**Comment by impressivewebs** [comment]
> [30 seconds of code](https://www.30secondsofcode.org/) is a collection of short code snippets and blogs, focused mainly on web development and especially JavaScript. We recently added an RSS feed to our website and I think this would fit right into this list.

Oh one more thing, the blogs are in alphabetical order, so yours would have to be up near the top. Are you able to edit it so yours is in the correct alphabetical listing in both files?

**Comment by Chalarangelo** [comment]
@impressivewebs Moved the links to be in the correct order. Take another look, if you can, please.

About Brave's behavior, no clue why honestly, but it could be related to Google Analytics or something like that (although we have Analytics disabled until the user accepts cookies). It could also be related to a gatsby plugin acting up, but that shouldn't be an issue any more. Will investigate regardless.

**Comment by impressivewebs** [comment]
> @impressivewebs Moved the links to be in the correct order. Take another look, if you can, please.
> 
> About Brave's behavior, no clue why honestly, but it could be related to Google Analytics or something like that (although we have Analytics disabled until the user accepts cookies). It could also be related to a gatsby plugin acting up, but that shouldn't be an issue any more. Will investigate regardless.

Yeah, I sense it's definitely a React thing. Does the page render without JS enabled? That might be another thing worth looking into, though I don't personally care so much about that.

**Comment by Chalarangelo** [comment]
@impressivewebs Yep, it does, although some parts of it might not operate 100% correctly without JS. Still entirely usable, though.

**Comment by impressivewebs** [comment]
> @impressivewebs Yep, it does, although some parts of it might not operate 100% correctly without JS. Still entirely usable, though.

Ok that's good.

I just realized, if I visit the page fresh with the ad block disabled, it still appears blank. Then the page renders if I enable ad block. Very weird.

**Pull request merged**
